### ISSUE TITLE
工程跑不起来

### ISSUE THREAD

**Issue by CoderLwcXing** [dKingbin/GoPlay#1]
Ld /Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Products/Debug-iphoneos/GoPlay.app/GoPlay normal arm64 (in target: GoPlay)
    cd /Users/l_wcx/Desktop/我的代码/gitHub/GoPlay/GoPlay
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.2.sdk -L/Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Products/Debug-iphoneos -L/Users/l_wcx/Desktop/我的代码/gitHub/GoPlay/GoPlay/GoPlay/Vendor/FFmpeg/FFmpeg-iOS/lib -F/Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Products/Debug-iphoneos -filelist /Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Intermediates.noindex/GoPlay.build/Debug-iphoneos/GoPlay.build/Objects-normal/arm64/GoPlay.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Intermediates.noindex/GoPlay.build/Debug-iphoneos/GoPlay.build/Objects-normal/arm64/GoPlay_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -stdlib=libc++ -fobjc-arc -fobjc-link-runtime -lavfilter -lbz2 -lz -lavformat -lswresample -liconv -framework VideoToolbox -lavutil -framework AVFoundation -lavdevice -lswscale -framework AudioToolbox -lavcodec -Xlinker -dependency_info -Xlinker /Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Intermediates.noindex/GoPlay.build/Debug-iphoneos/GoPlay.build/Objects-normal/arm64/GoPlay_dependency_info.dat -o /Users/l_wcx/Library/Developer/Xcode/DerivedData/GoPlay-fiamenkbxaxnbqclkhxyrwdpstrd/Build/Products/Debug-iphoneos/GoPlay.app/GoPlay

**Comment by CoderLwcXing** [comment]
ld: warning: directory not found for option '-L/Users/l_wcx/Desktop/我的代码/gitHub/GoPlay/GoPlay/GoPlay/Vendor/FFmpeg/FFmpeg-iOS/lib'
ld: library not found for -lavfilter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CoderLwcXing** [comment]
FFmpeg  编译完成之后还是跑不起来，报错

**Comment by letqingbin** [comment]
@LwcXing 加一下群: 527359948
你的FFmpeg库应该是没有编译成功

**Comment by CoderLwcXing** [comment]
编译成功了，静态库什么的都有了

**Comment by letqingbin** [comment]
@LwcXing 之前是什么原因？我总结一下给以后的人~

**Comment by letqingbin** [comment]
@LwcXing 如果编译成功，那你设置一下头文件的路径
1) 拷贝 ./FFmpeg-iOS 到 ./GoPlay/GoPlay/Vendor/FFmpeg/ 
2) 配置工程项目的FFmpeg头文件路径: Build Settings - Header Search Paths - "$(SRCROOT)/GoPlay/Vendor/FFmpeg/FFmpeg-iOS/include"

**Comment by CoderLwcXing** [comment]
_下载工程，本来应该就是跑步起来了的，我运行了文件里的脚本，自动下载FFmpeg并编译、成功后，重新添加静态库后，还是报错如下：_
ld: warning: directory not found for option '-L/Users/l_wcx/Desktop/我的代码/gitHub/GoPlay/GoPlay/GoPlay/Vendor/FFmpeg/FFmpeg-iOS/lib'
ld: library not found for -lavfilter
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by letqingbin** [comment]
1、你到GoPlay/GoPlay/Vendor/FFmpeg/这个目录下检查有没有FFmpeg-iOS/include 和 FFmpeg-iOS/lib, 如果没有说明你编译库文件出错
2、打开工程，看一下工程目录有没有引进Vendor/FFmpeg-iOS
3、去工程项目配置中，查看有没有设置头文件路径

这三步如果都没问题，那么加群再详聊，群里的人都是没这个问题的

**Comment by CoderLwcXing** [comment]
你说的这些都有，但是就是报错，已加入，截图发群里了

**Comment by letqingbin** [comment]
问题已解决
