### ISSUE TITLE
Hls adaptive bitrate

### ISSUE THREAD

**Issue by minhtoantm** [dKingbin/GoPlay#6]
Hi.
Thanks for great player.
But can you implemnt function: hls adaptive bitrate when playing m3u8 master playlist?
Example: https://mnmedias.api.telequebec.tv/m3u8/29880.m3u8

When I play master m3u8, always play the first playlist, not by bandwidth.
Thank you again.

**Comment by letqingbin** [comment]
Your provided URL cannot be played by ffplay as well, Please provide a valid URL, thanks.
